name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build --file Dockerfile -t ci-cd-example .
    - name: Tags
        run: |
          docker tag ci-cd-example ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-example:${{ github.sha }}
          docker tag ci-cd-example ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-example:latest
    - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-example:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-example:latest
