name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag biolounge/ci-cd-example:$(date +%s)
    - name: Push the latest Docker image
      run: docker push biolounge/ci-cd-example:$(date +%s)
